language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

os:
  - linux
  - osx

services:
  - mongodb
  - postgresql

before_script:
  - pip install pymongo requests psycopg2 psutil elasticsearch
  - sudo mkdir /opt/grease/
  - sudo chmod 777 /opt/grease/
  - if [ $TRAVIS_OS_NAME = linux ]; then true; else brew install mongo; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then true; else brew services start mongodb; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then rm -rf /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then initdb /usr/local/var/postgres; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pg_ctl -D /usr/local/var/postgres start; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then createuser -s postgres; fi

install:
  - python setup.py install
  
script:
  - python setup.py test
# Run twice to ensure state management is successful
  - python setup.py test
  - grease bridge register --foreground
  - grease help
  - grease daemon run --loop:5 --foreground
  - grease scan --loop:5 --foreground
  - grease detect --loop:5 --foreground
  - grease schedule --loop:5 --foreground
  - grease monitor --loop:5 --foreground
  - grease bridge assign --prototype:scan
  - grease bridge assign --prototype:detect
  - grease bridge assign --prototype:schedule
  - grease bridge info --jobs --pJobs
  - grease bridge unassign --prototype:scan
  - grease bridge unassign --prototype:detect
  - grease bridge unassign --prototype:schedule
  - grease bridge cull

deploy:
  on:
    branch: master
  provider: pypi
  user: $PYPI_USER
  password: 
    secure: $PYPI_PASSWORD
