language: python

python:
  - "2.7" #what we built it for originally
  - "nightly" #whatever 3.x is hemorrhaging-edge

services:
  - postgresql

before_script:
  - pip install psycopg2 pymongo requests sqlalchemy
  - export GREASE_DB_ENGINE="postgresql"
  - export GREASE_DB_USER="postgres"
  - export GREASE_DB_PASSWORD=""
  - export GREASE_PKG_LOADER="tgt_grease_"
  - export GREASE_VERBOSE_LOGGING=1
  - python ./bin/install_db.py

install:
  - python setup.py install
  
script:
  - python setup.py test
  - grease enterprise bridge register
  - grease enterprise bridge list-pjobs
  - grease enterprise bridge list-jobs

matrix:
  allow_failures:
    - python: nightly

deploy:
  on:
    branch: master
  provider: pypi
  user: $PYPI_USER
  password: 
    secure: $PYPI_PASSWORD
