language: python

python:
  - "2.7" #what we built it for originally
  - "nightly" #whatever 3.x is hemorrhaging-edge

services:
  - postgresql

before_script:
  - pip install psycopg2 pymongo requests sqlalchemy
  - export GREASE_DB_USER="postgres"
  - python ./bin/install_db.py

install:
  - python setup.py install
  
script:
  - python setup.py test

matrix:
  allow_failures:
    - python: nightly

deploy:
  on:
    branch: master
  provider: pypi
  user: $PYPI_USER
  password: 
    secure: $PYPI_PASSWORD
