language: python

sudo: required

python:
  - "2.7" #what we built it for originally
  - "nightly" #whatever 3.x is hemorrhaging-edge

services:
  - mongodb

before_script:
  - pip install pymongo requests

install:
  - python setup.py install
  
script:
  - python setup.py test
# TODO: Redo Node Tests
  - grease help
#  - grease enterprise bridge list-pjobs
#  - grease enterprise bridge list-jobs
#  - grease enterprise bridge enable-detection
#  - grease enterprise bridge enable-scheduling
#  - grease enterprise bridge disable-detection
#  - grease enterprise bridge disable-scheduling
#  - grease enterprise bridge kill-server

deploy:
  on:
    branch: master
  provider: pypi
  user: $PYPI_USER
  password: 
    secure: $PYPI_PASSWORD
