language: python

matrix:
  fast_finish: true
  allowed_failures:
  - osx_image: xcode9.1
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: "2.7"
    - os: linux
      sudo: required
      dist: trusty
      python: "nightly"
    - os: osx
      sudo: required
      osx_image: xcode9.1
      rvm: 2.3
      python: "2.7"
    - os: osx
      sudo: required
      osx_image: xcode9.1
      rvm: 2.3
      python: "nightly"

services:
  - mongodb

before_script:
  - pip install pymongo requests
  - sudo mkdir /opt/grease/
  - sudo chmod 777 /opt/grease/
  - if [ $TRAVIS_OS_NAME = linux ]; then true; else brew update; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then true; else brew upgrade; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then true; else brew install mongo; fi

install:
  - python setup.py install
  
script:
  - python setup.py test
# TODO: Redo Node Tests
  - grease help
  - grease daemon run --timing:5
#  - grease enterprise bridge list-pjobs
#  - grease enterprise bridge list-jobs
#  - grease enterprise bridge enable-detection
#  - grease enterprise bridge enable-scheduling
#  - grease enterprise bridge disable-detection
#  - grease enterprise bridge disable-scheduling
#  - grease enterprise bridge kill-server

deploy:
  on:
    branch: master
  provider: pypi
  user: $PYPI_USER
  password: 
    secure: $PYPI_PASSWORD
