language: python

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      python: "2.7"
    - os: linux
      sudo: required
      dist: trusty
      python: "nightly"
    - os: osx
      sudo: required
      python: "2.7"
    - os: osx
      sudo: required
      python: "nightly"

services:
  - mongodb

before_script:
  - pip install pymongo requests

install:
  - python setup.py install
  
script:
  - python setup.py test
# TODO: Redo Node Tests
  - grease help
  - grease daemon run --timing:5
#  - grease enterprise bridge list-pjobs
#  - grease enterprise bridge list-jobs
#  - grease enterprise bridge enable-detection
#  - grease enterprise bridge enable-scheduling
#  - grease enterprise bridge disable-detection
#  - grease enterprise bridge disable-scheduling
#  - grease enterprise bridge kill-server

deploy:
  on:
    branch: master
  provider: pypi
  user: $PYPI_USER
  password: 
    secure: $PYPI_PASSWORD
